---

- name: Create Directory for the App
  file: 
    state: directory
    path: "{{App_dir}}"

- name: Install Python3 and pip3
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - python3   
    - python3-pip
    - git
    - python-pip

- name: Install needed packages for flaskapp using pip3
  pip:
    name: 
      - flask
      - flask-mysqldb
    executable: pip3
    
- name: clone the git repo
  git:
    repo: https://github.com/sanjaysureshmv/python_restful.git
    dest: "{{App_dir}}"
    clone: yes
    
- name : Ensure the app is started
  shell: nohup python3 app.py &
  args:
    chdir: "{{App_dir}}"
    executable: /bin/bash

      

    
